import _CryptoExtras
import CryptoKit
import Foundation
import os
import SwiftASN1
import X509

/// The certificate authorities and the DC's TLS server certificate.
///
/// State lives in one directory (created 0700): `ca.pem`, `ca-key.pem` (the lab CA, named
/// `lab`), `server.pem`, `server-key.pem`, each 0600, private keys as PKCS#8 PEM. PK-1 adds more
/// CAs, one directory each: `cas/<name>/ca.pem` + `ca-key.pem` (P-256 or RSA-2048/3072), and
/// `current-ca.json` naming the CA that issues (absent: the lab CA). `ensureCA` and
/// `ensureServerCertificate` are idempotent: they reuse what is on disk while it still matches
/// and regenerate it otherwise. The DC certificate is signed by the current CA.
///
/// Key types (owner, 1 Oct 2026): a NEW lab CA is P-384 / ECDSA-SHA384 and the DC certificate
/// issued by a P-384 CA has a P-384 key. An existing lab CA keeps its type (P-256 domains stay
/// P-256 — never re-keyed by an upgrade), and whatever key type is on disk (P-256 or P-384) loads.
public actor LabPKI {
    /// Result of an `ensure…` call.
    public enum Outcome: Sendable, Equatable {
        /// The existing certificate still matches the request and was kept.
        case unchanged
        /// A new certificate (and key) was generated and written.
        case issued
    }

    public enum ExportFormat: Sendable {
        case pem
        case der
    }

    /// The names a server certificate is issued for.
    public struct SubjectAltNames: Sendable, Equatable {
        public var hostnames: [String]
        public var ips: [String]
        public init(hostnames: [String], ips: [String]) {
            self.hostnames = hostnames
            self.ips = ips
        }
    }

    public static let caCertificateFileName = "ca.pem"
    public static let caKeyFileName = "ca-key.pem"
    public static let serverCertificateFileName = "server.pem"
    public static let serverKeyFileName = "server-key.pem"
    /// Names the current CA (`{"current": "<name>"}`); absent means the lab CA.
    public static let currentCAFileName = "current-ca.json"
    /// Sub-directory holding the CAs created with `createCA`, one directory per CA.
    public static let casDirectoryName = "cas"
    /// The name of the lab CA (the files at the top of the PKI directory).
    public static let labCAName = "lab"
    /// WPA3-Enterprise 192-bit (1 Oct 2026): a second root, P-384 / SHA-384, for 802.1X only —
    /// the lab CA (P-256) and everything it issued stay as they are.
    public static let suiteBCAName = "dot1x-suiteb"
    /// The RADIUS server certificate under that root (P-384, serverAuth, the DC's FQDN).
    public static let suiteBServerCertificateFileName = "radius-suiteb.pem"
    public static let suiteBServerKeyFileName = "radius-suiteb-key.pem"
    /// Old devices that only do RSA (1 Oct 2026, opt-in): a separate RSA-3072 / SHA-256 root for
    /// 802.1X, created when "Allow RSA-only devices" is switched on; existing CAs are untouched.
    public static let rsaCompatCAName = "rsa-compat"
    /// Its RADIUS server certificate (RSA-2048, serverAuth, the DC's FQDN).
    public static let rsaServerCertificateFileName = "radius-rsa.pem"
    public static let rsaServerKeyFileName = "radius-rsa-key.pem"

    static let caLifetimeYears = 10
    static let serverLifetimeDays = 825
    /// Certificates closer than this to `notAfter` are regenerated by `ensure…`.
    static let renewBefore: TimeInterval = 30 * 86400
    /// `notBefore` is back-dated this much to tolerate client clock skew.
    static let backdate: TimeInterval = 300

    private struct Pair {
        var certificate: Certificate
        var key: ServerKey
    }

    public nonisolated let directory: URL
    /// The lab CA (top-level files).
    private var lab: CertificateAuthority?
    /// CAs under `cas/`, loaded on first use.
    private var others: [String: CertificateAuthority] = [:]
    /// The CA that issues (the DC certificate and `CAService.issue`).
    public private(set) var currentCAName: String = LabPKI.labCAName
    private var server: Pair?
    private var suiteBServer: (certificate: Certificate, key: P384.Signing.PrivateKey)?
    private var rsaServer: (certificate: Certificate, key: _RSA.Signing.PrivateKey)?
    /// The key type of a lab CA created where none exists (a new domain): P-384 since 1 Oct 2026.
    public static let defaultLabCAKeyType: CAKeyType = .p384
    private let logger = Logger(subsystem: "dev.labdc.app", category: "pki")

    private init(directory: URL) {
        self.directory = directory
    }

    /// Opens (creating it 0700 if needed) the PKI directory and loads whatever is there.
    ///
    /// A certificate whose key file is missing or does not match is ignored (it is regenerated by
    /// the next `ensure…` call). A file that is not valid PEM throws `corruptFile`.
    public static func open(directory: URL) async throws -> LabPKI {
        try SecureFiles.ensureDirectory(directory)
        let pki = LabPKI(directory: directory)
        try await pki.load()
        return pki
    }

    // MARK: - Lab CA

    /// Makes sure the lab CA with subject `CN=<name>` exists and is not about to expire.
    ///
    /// A lab CA that is not the current CA is left as it is (no re-key, no rename).
    ///
    /// A new lab CA (different name, missing, expiring within 30 days) invalidates the server
    /// certificate when the lab CA is current: it is removed and must be reissued with
    /// `ensureServerCertificate`.
    ///
    /// `alsoAccepting`: former names of the same CA (the app was SheepAuth until 1 Oct 2026, and
    /// its lab CA is `CN=SheepAuth Lab CA (<realm>)`). A current CA under one of them is kept as
    /// it is: joined PCs trust that key, so a rename never re-keys (owner, 1 Oct 2026).
    ///
    /// `keyType`: the key of a lab CA created where there is none (default P-384). A lab CA that
    /// is replaced (renamed, expiring) keeps the type it had, so a P-256 domain stays P-256.
    @discardableResult
    public func ensureCA(name: String, alsoAccepting formerNames: [String] = [],
                         keyType: CAKeyType = LabPKI.defaultLabCAKeyType) throws -> Outcome {
        let subject = try DistinguishedName { CommonName(name) }
        let accepted = try [subject] + formerNames.map { n in try DistinguishedName { CommonName(n) } }
        let now = Date()
        if let lab, accepted.contains(lab.certificate.subject),
           lab.certificate.notValidAfter > now.addingTimeInterval(Self.renewBefore) {
            return .unchanged
        }
        // A lab CA that no longer issues (a root migration made another CA current, and retired
        // it or will) is never re-keyed or renamed: it only keeps publishing its CRL.
        if lab != nil, currentCAName.lowercased() != Self.labCAName { return .unchanged }

        let key = try CASigningKey.generate(lab?.keyType ?? keyType)
        let certificate = try Self.makeCACertificate(subject: subject, key: key, years: Self.caLifetimeYears,
                                                     maxPathLength: 0, now: now)
        // Key first, then certificate: a crash in between leaves a mismatching pair, which
        // `loadAuthority` discards.
        try SecureFiles.write(Array(key.pemRepresentation.utf8), to: url(Self.caKeyFileName))
        try SecureFiles.write(Array(Self.pem(certificate).utf8), to: url(Self.caCertificateFileName))
        lab = CertificateAuthority(name: Self.labCAName, certificate: certificate, key: key, directory: directory)
        if server != nil, currentCAName == Self.labCAName {
            server = nil
            unlink(url(Self.serverCertificateFileName).path)
            unlink(url(Self.serverKeyFileName).path)
        }
        logger.info("issued lab CA '\(name, privacy: .public)' (\(key.keyType.displayName, privacy: .public)) serial \(Self.hex(certificate.serialNumber), privacy: .public)")
        return .issued
    }

    // MARK: - More CAs (PK-1)

    /// Creates a CA `name` (subject `CN=<commonName ?? name>`) valid for `years` calendar years
    /// in `cas/<name>/`. It does not become current (see `useCA`).
    ///
    /// Names are 1–64 characters of `A–Z a–z 0–9 . _ -` starting with a letter or digit (they
    /// appear in the CDP/AIA URLs `http://<dc>/pki/<name>.crl`); `lab` is the lab CA's.
    @discardableResult
    public func createCA(name: String, commonName: String? = nil, keyType: CAKeyType = .p256,
                         years: Int = 10) throws -> CertificateAuthority {
        guard Self.isValidCAName(name) else { throw PKIKitError.invalidCAName(name) }
        guard (1...50).contains(years) else { throw PKIKitError.invalidCALifetime(years) }
        let existing = try authorityIfExists(named: name)
        if name.lowercased() == Self.labCAName || existing != nil { throw PKIKitError.caExists(name) }
        let cn = commonName.flatMap { $0.isEmpty ? nil : $0 } ?? name
        let subject = try DistinguishedName { CommonName(cn) }
        let key = try CASigningKey.generate(keyType)
        let certificate = try Self.makeCACertificate(subject: subject, key: key, years: years, maxPathLength: nil,
                                                     now: Date())
        let dir = caDirectory(name)
        try SecureFiles.ensureDirectory(dir.deletingLastPathComponent())
        try SecureFiles.ensureDirectory(dir)
        try SecureFiles.write(Array(key.pemRepresentation.utf8), to: dir.appendingPathComponent(Self.caKeyFileName))
        try SecureFiles.write(Array(Self.pem(certificate).utf8), to: dir.appendingPathComponent(Self.caCertificateFileName))
        let ca = CertificateAuthority(name: name, certificate: certificate, key: key, directory: dir)
        others[name] = ca
        logger.info("created CA '\(name, privacy: .public)' (\(keyType.displayName, privacy: .public)) serial \(Self.hex(certificate.serialNumber), privacy: .public)")
        return ca
    }

    /// Every CA: the lab CA first (when it exists), then the others by name.
    public func authorities() throws -> [CertificateAuthority] {
        var result: [CertificateAuthority] = []
        if let lab { result.append(lab) }
        for name in caDirectoryNames() {
            if let ca = try authorityIfExists(named: name) { result.append(ca) }
        }
        return result
    }

    /// The CA called `name` (`lab` or one from `createCA`); throws `unknownCA` when there is none.
    public func authority(named name: String) throws -> CertificateAuthority {
        guard let ca = try authorityIfExists(named: name) else {
            if name.lowercased() == Self.labCAName { throw PKIKitError.caNotInitialized }
            throw PKIKitError.unknownCA(name)
        }
        return ca
    }

    /// The CA that issues: the one named in `current-ca.json`, else the lab CA.
    public func currentAuthority() throws -> CertificateAuthority {
        try authority(named: currentCAName)
    }

    /// Makes `name` the current CA. The DC certificate then no longer chains to the current CA,
    /// so the next `ensureServerCertificate` (at the next `serve` start) reissues it.
    public func useCA(name: String) throws {
        let ca = try authority(named: name)
        let json = try JSONEncoder().encode(["current": ca.name])
        try SecureFiles.write(Array(json), to: url(Self.currentCAFileName))
        currentCAName = ca.name
        logger.info("current CA is now '\(ca.name, privacy: .public)'")
    }

    /// The directory of CA `name` (the PKI directory itself for the lab CA).
    public nonisolated func caDirectory(_ name: String) -> URL {
        name.lowercased() == Self.labCAName ? directory
            : directory.appendingPathComponent(Self.casDirectoryName).appendingPathComponent(name, isDirectory: true)
    }

    public static func isValidCAName(_ name: String) -> Bool {
        guard (1...64).contains(name.utf8.count), let first = name.utf8.first else { return false }
        let alnum = { (c: UInt8) in (c >= 0x30 && c <= 0x39) || (c >= 0x41 && c <= 0x5A) || (c >= 0x61 && c <= 0x7A) }
        guard alnum(first) else { return false }
        return name.utf8.allSatisfy { alnum($0) || $0 == 0x2E || $0 == 0x5F || $0 == 0x2D }
    }

    private func caDirectoryNames() -> [String] {
        let casURL = directory.appendingPathComponent(Self.casDirectoryName)
        let names = (try? FileManager.default.contentsOfDirectory(atPath: casURL.path)) ?? []
        return names.filter(Self.isValidCAName).sorted()
    }

    private func authorityIfExists(named name: String) throws -> CertificateAuthority? {
        if name.lowercased() == Self.labCAName { return lab }
        guard Self.isValidCAName(name) else { return nil }
        if let cached = others[name] { return cached }
        // Case-insensitive file systems: use the directory's own spelling.
        guard let exact = caDirectoryNames().first(where: { $0.lowercased() == name.lowercased() }) else { return nil }
        if let cached = others[exact] { return cached }
        guard let ca = try loadAuthority(name: exact, directory: caDirectory(exact)) else { return nil }
        others[exact] = ca
        return ca
    }

    static func makeCACertificate(subject: DistinguishedName, key: CASigningKey, years: Int, maxPathLength: Int?,
                                  now: Date) throws -> Certificate {
        let publicKey = key.publicKey
        let notBefore = now.addingTimeInterval(-Self.backdate)
        guard let notAfter = Calendar(identifier: .gregorian).date(byAdding: .year, value: years, to: notBefore)
        else { throw PKIKitError.encoding("cannot compute CA expiry") }
        do {
            let extensions = try Certificate.Extensions {
                Critical(BasicConstraints.isCertificateAuthority(maxPathLength: maxPathLength))
                Critical(KeyUsage(keyCertSign: true, cRLSign: true))
                SubjectKeyIdentifier(hash: publicKey)
            }
            return try Certificate(
                version: .v3,
                serialNumber: Self.randomSerial(),
                publicKey: publicKey,
                notValidBefore: notBefore,
                notValidAfter: notAfter,
                issuer: subject,
                subject: subject,
                signatureAlgorithm: key.signatureAlgorithm,
                extensions: extensions,
                issuerPrivateKey: key.certificateKey
            )
        } catch {
            throw PKIKitError.encoding("CA certificate: \(error)")
        }
    }

    // MARK: - Server certificate

    /// Makes sure the server certificate carries exactly these SAN entries, is signed by the
    /// current CA and is not about to expire. The first host name is the subject CN.
    ///
    /// Host names are compared case-insensitively (stored lower-case, trailing dot removed) and
    /// IPs by their binary value; order and duplicates do not matter.
    @discardableResult
    public func ensureServerCertificate(hostnames: [String], ips: [String]) throws -> Outcome {
        let ca = try currentAuthority()
        let names = try Self.canonicalNames(hostnames: hostnames, ips: ips)
        let subject = try DistinguishedName { CommonName(names.hostnames[0]) }
        let wanted = Set(names.generalNames)
        let now = Date()

        if let server,
           server.certificate.subject == subject,
           Self.isIssued(server.certificate, by: ca.certificate),
           server.certificate.notValidAfter > now.addingTimeInterval(Self.renewBefore),
           let sans = try? server.certificate.extensions.subjectAlternativeNames,
           Set(sans) == wanted {
            return .unchanged
        }

        // The key follows the CA: P-384 under a P-384 CA, else P-256 (as it always was).
        let key = ServerKey.generate(issuedBy: ca.keyType)
        let publicKey = key.publicKey
        let notBefore = now.addingTimeInterval(-Self.backdate)
        let notAfter = min(notBefore.addingTimeInterval(TimeInterval(Self.serverLifetimeDays) * 86400),
                           ca.certificate.notValidAfter)
        let certificate: Certificate
        do {
            guard let caKeyID = try ca.certificate.extensions.subjectKeyIdentifier?.keyIdentifier else {
                throw PKIKitError.encoding("CA has no subjectKeyIdentifier")
            }
            let eku = try ExtendedKeyUsage([.serverAuth])
            let extensions = try Certificate.Extensions {
                Critical(BasicConstraints.notCertificateAuthority)
                Critical(KeyUsage(digitalSignature: true))
                eku
                SubjectKeyIdentifier(hash: publicKey)
                AuthorityKeyIdentifier(keyIdentifier: caKeyID)
                SubjectAlternativeNames(names.generalNames)
            }
            certificate = try Certificate(
                version: .v3,
                serialNumber: Self.randomSerial(),
                publicKey: publicKey,
                notValidBefore: notBefore,
                notValidAfter: notAfter,
                issuer: ca.certificate.subject,
                subject: subject,
                signatureAlgorithm: ca.key.signatureAlgorithm,
                extensions: extensions,
                issuerPrivateKey: ca.key.certificateKey
            )
        } catch let error as PKIKitError {
            throw error
        } catch {
            throw PKIKitError.encoding("server certificate: \(error)")
        }

        try write(Pair(certificate: certificate, key: key),
                  certificateFile: Self.serverCertificateFileName, keyFile: Self.serverKeyFileName)
        server = Pair(certificate: certificate, key: key)
        let list = (names.hostnames + names.ips).joined(separator: ", ")
        logger.info("issued server certificate serial \(Self.hex(certificate.serialNumber), privacy: .public) from CA \(ca.name, privacy: .public) for \(list, privacy: .public)")
        return .issued
    }

    /// The SAN set the phase-1 spec asks for: the DC name, the domain, `localhost`, every IPv4
    /// of this Mac and `127.0.0.1`.
    public static func defaultServerNames(dcHostname: String, dnsDomain: String) -> SubjectAltNames {
        SubjectAltNames(hostnames: [dcHostname, dnsDomain, "localhost"],
                        ips: currentAddresses() + ["127.0.0.1"])
    }

    /// IPv4 addresses of this Mac (interfaces up; no loopback, no 169.254/16).
    public static func currentAddresses() -> [String] {
        NetworkAddresses.currentIPv4()
    }

    // MARK: - Accessors

    /// The current CA's certificate (the lab CA unless `useCA` chose another).
    public func caCertificate() throws -> Certificate {
        try currentAuthority().certificate
    }

    public func serverCertificate() throws -> Certificate {
        guard let server else { throw PKIKitError.serverCertificateNotInitialized }
        return server.certificate
    }

    public func caPEM() throws -> String {
        try Self.pem(caCertificate())
    }

    public func caDER() throws -> [UInt8] {
        try Self.der(caCertificate())
    }

    public func serverPEM() throws -> String {
        try Self.pem(serverCertificate())
    }

    /// The server private key, PKCS#8 PEM (`-----BEGIN PRIVATE KEY-----`).
    public func serverKeyPEM() throws -> String {
        guard let server else { throw PKIKitError.serverCertificateNotInitialized }
        return server.key.pemRepresentation
    }

    /// Phase 4b (RADIUS/EAP): the DC certificate — issued at start for the DC's FQDN with the
    /// serverAuth EKU — then its issuing CA (DER), and the key as PKCS#8 DER. Windows checks the
    /// FQDN against the 802.1X profile's ServerNames and the CA against its TrustedRootCA.
    public func eapServerCredentials() throws -> (chain: [[UInt8]], keyDER: [UInt8]) {
        guard let server else { throw PKIKitError.serverCertificateNotInitialized }
        var chain = [try Self.der(server.certificate)]
        if let issuer = try authorities().first(where: { Self.isIssued(server.certificate, by: $0.certificate) }) {
            chain.append(try issuer.der())
        }
        return (chain, server.key.derRepresentation)
    }

    // MARK: - WPA3-Enterprise 192-bit

    /// Whether the P-384 802.1X root exists (it is created on first use: `CAService.ensureSuiteBAuthority`).
    public func hasSuiteBCA() throws -> Bool { try authorityIfExists(named: Self.suiteBCAName) != nil }

    /// Whether the current CA itself serves WPA3-Enterprise 192-bit: it is P-384 (a domain
    /// provisioned since 1 Oct 2026) and no separate 802.1X 192-bit CA exists. Then no second
    /// root is made: the DC certificate (P-384, ECDSA-SHA384) is the RADIUS certificate for
    /// 192-bit clients too, and the `Computer192` / `User192` templates are issued by the
    /// current CA. A P-256 domain keeps the separate `dot1x-suiteb` CA, as does a P-384 domain
    /// that already has one.
    public func mainCAServesSuiteB() throws -> Bool {
        guard try authorityIfExists(named: Self.suiteBCAName) == nil else { return false }
        return (try? currentAuthority())?.keyType == .p384
    }

    /// The root WPA3-Enterprise 192-bit clients trust: the 802.1X 192-bit CA when it exists,
    /// else the current CA when it is P-384; nil when neither (the 192-bit CA is still to be made).
    public func suiteBAuthority() throws -> CertificateAuthority? {
        if let ca = try authorityIfExists(named: Self.suiteBCAName) { return ca }
        guard let current = try? currentAuthority(), current.keyType == .p384 else { return nil }
        return current
    }

    /// The CA that issues for a template whose `issuingCA` is `name`: that CA — except the
    /// 802.1X 192-bit CA's name while the current CA serves 192-bit itself (`mainCAServesSuiteB`).
    public func issuingAuthority(named name: String) throws -> CertificateAuthority {
        if name.lowercased() == Self.suiteBCAName, try mainCAServesSuiteB() { return try currentAuthority() }
        return try authority(named: name)
    }

    /// Makes sure the P-384 802.1X root exists (`cas/dot1x-suiteb`, 10 years). It is an ordinary
    /// LabDC CA: published to the Configuration NC and NTAuth with the others, trusted for
    /// EAP-TLS client certificates, and the issuer of the `Computer192` / `User192` templates.
    @discardableResult
    public func ensureSuiteBCA(commonName: String) throws -> Outcome {
        if let ca = try authorityIfExists(named: Self.suiteBCAName) {
            guard ca.keyType == .p384 else {
                throw PKIKitError.encoding("CA \(Self.suiteBCAName) exists but is \(ca.keyType.displayName), not P-384")
            }
            return .unchanged
        }
        try createCA(name: Self.suiteBCAName, commonName: commonName, keyType: .p384, years: Self.caLifetimeYears)
        return .issued
    }

    /// The P-384 RADIUS server certificate for `hostname` (serverAuth, dNSName = the DC's FQDN,
    /// ECDSA-SHA384 by the 802.1X P-384 root), reissued when missing, renamed, re-rooted or
    /// close to expiry. What WPA3-Enterprise 192-bit clients get.
    @discardableResult
    public func ensureSuiteBServerCertificate(hostname: String) throws -> Outcome {
        let ca = try authority(named: Self.suiteBCAName)
        let names = try Self.canonicalNames(hostnames: [hostname], ips: [])
        let subject = try DistinguishedName { CommonName(names.hostnames[0]) }
        let now = Date()
        if let current = suiteBServer, current.certificate.subject == subject, Self.isIssued(current.certificate, by: ca.certificate),
           current.certificate.notValidAfter > now.addingTimeInterval(Self.renewBefore) {
            return .unchanged
        }
        let key = P384.Signing.PrivateKey()
        let publicKey = Certificate.PublicKey(key.publicKey)
        let notBefore = now.addingTimeInterval(-Self.backdate)
        let notAfter = min(notBefore.addingTimeInterval(TimeInterval(Self.serverLifetimeDays) * 86400), ca.certificate.notValidAfter)
        let certificate: Certificate
        do {
            guard let caKeyID = try ca.certificate.extensions.subjectKeyIdentifier?.keyIdentifier else {
                throw PKIKitError.encoding("CA has no subjectKeyIdentifier")
            }
            let extensions = try Certificate.Extensions {
                Critical(BasicConstraints.notCertificateAuthority)
                Critical(KeyUsage(digitalSignature: true))
                try ExtendedKeyUsage([.serverAuth])
                SubjectKeyIdentifier(hash: publicKey)
                AuthorityKeyIdentifier(keyIdentifier: caKeyID)
                SubjectAlternativeNames(names.generalNames)
            }
            certificate = try Certificate(version: .v3, serialNumber: Self.randomSerial(), publicKey: publicKey,
                                          notValidBefore: notBefore, notValidAfter: notAfter, issuer: ca.certificate.subject,
                                          subject: subject, signatureAlgorithm: ca.key.signatureAlgorithm, extensions: extensions,
                                          issuerPrivateKey: ca.key.certificateKey)
        } catch let error as PKIKitError {
            throw error
        } catch {
            throw PKIKitError.encoding("192-bit RADIUS certificate: \(error)")
        }
        try SecureFiles.write(Array(key.pemRepresentation.utf8), to: url(Self.suiteBServerKeyFileName))
        try SecureFiles.write(Array(Self.pem(certificate).utf8), to: url(Self.suiteBServerCertificateFileName))
        suiteBServer = (certificate, key)
        logger.info("issued 192-bit RADIUS certificate serial \(Self.hex(certificate.serialNumber), privacy: .public) for \(names.hostnames[0], privacy: .public)")
        return .issued
    }

    /// The 192-bit RADIUS certificate (nil before `ensureSuiteBServerCertificate`).
    public func suiteBServerCertificate() -> Certificate? { suiteBServer?.certificate }

    /// The 192-bit EAP credential: the P-384 leaf, the P-384 root, the key as PKCS#8 DER. When
    /// the current CA serves 192-bit itself, the DC certificate (P-384 key, ECDSA-SHA384 by that
    /// P-384 root) is that credential; nil while it is not P-384 yet.
    public func eapSuiteBCredentials() throws -> (chain: [[UInt8]], keyDER: [UInt8])? {
        if let ca = try authorityIfExists(named: Self.suiteBCAName) {
            guard let suiteBServer else { return nil }
            return ([try Self.der(suiteBServer.certificate), try ca.der()], Array(suiteBServer.key.derRepresentation))
        }
        guard let server, server.key.isP384, let ca = try suiteBAuthority(),
              Self.isIssued(server.certificate, by: ca.certificate) else { return nil }
        return ([try Self.der(server.certificate), try ca.der()], server.key.derRepresentation)
    }

    // MARK: - RSA-only devices

    /// Whether the RSA compatibility root exists (created by `CAService.setRSACompatibility(true)`).
    public func hasRSACompatCA() throws -> Bool { try authorityIfExists(named: Self.rsaCompatCAName) != nil }

    /// Makes sure the RSA compatibility root exists (`cas/rsa-compat`, RSA-3072 / SHA-256, 10
    /// years). It never becomes current: the main CA keeps issuing for Windows.
    @discardableResult
    public func ensureRSACompatCA(commonName: String) throws -> Outcome {
        if let ca = try authorityIfExists(named: Self.rsaCompatCAName) {
            guard ca.keyType == .rsa3072 || ca.keyType == .rsa2048 else {
                throw PKIKitError.encoding("CA \(Self.rsaCompatCAName) exists but is \(ca.keyType.displayName), not RSA")
            }
            return .unchanged
        }
        try createCA(name: Self.rsaCompatCAName, commonName: commonName, keyType: .rsa3072, years: Self.caLifetimeYears)
        return .issued
    }

    /// The RSA RADIUS server certificate for `hostname` (RSA-2048, serverAuth, dNSName = the
    /// DC's FQDN, SHA-256 by the RSA compatibility root; digitalSignature + keyEncipherment so
    /// TLS_RSA key transport works for the oldest supplicants), reissued when missing, renamed,
    /// re-rooted or close to expiry.
    @discardableResult
    public func ensureRSAServerCertificate(hostname: String) throws -> Outcome {
        let ca = try authority(named: Self.rsaCompatCAName)
        let names = try Self.canonicalNames(hostnames: [hostname], ips: [])
        let subject = try DistinguishedName { CommonName(names.hostnames[0]) }
        let now = Date()
        if let current = rsaServer, current.certificate.subject == subject, Self.isIssued(current.certificate, by: ca.certificate),
           current.certificate.notValidAfter > now.addingTimeInterval(Self.renewBefore) {
            return .unchanged
        }
        let key: _RSA.Signing.PrivateKey
        do { key = try _RSA.Signing.PrivateKey(keySize: .bits2048) } catch {
            throw PKIKitError.encoding("RSA key generation: \(error)")
        }
        let publicKey = Certificate.PublicKey(key.publicKey)
        let notBefore = now.addingTimeInterval(-Self.backdate)
        let notAfter = min(notBefore.addingTimeInterval(TimeInterval(Self.serverLifetimeDays) * 86400), ca.certificate.notValidAfter)
        let certificate: Certificate
        do {
            guard let caKeyID = try ca.certificate.extensions.subjectKeyIdentifier?.keyIdentifier else {
                throw PKIKitError.encoding("CA has no subjectKeyIdentifier")
            }
            let extensions = try Certificate.Extensions {
                Critical(BasicConstraints.notCertificateAuthority)
                Critical(KeyUsage(digitalSignature: true, keyEncipherment: true))
                try ExtendedKeyUsage([.serverAuth])
                SubjectKeyIdentifier(hash: publicKey)
                AuthorityKeyIdentifier(keyIdentifier: caKeyID)
                SubjectAlternativeNames(names.generalNames)
            }
            certificate = try Certificate(version: .v3, serialNumber: Self.randomSerial(), publicKey: publicKey,
                                          notValidBefore: notBefore, notValidAfter: notAfter, issuer: ca.certificate.subject,
                                          subject: subject, signatureAlgorithm: ca.key.signatureAlgorithm, extensions: extensions,
                                          issuerPrivateKey: ca.key.certificateKey)
        } catch let error as PKIKitError {
            throw error
        } catch {
            throw PKIKitError.encoding("RSA RADIUS certificate: \(error)")
        }
        try SecureFiles.write(Array(key.pkcs8PEMRepresentation.utf8), to: url(Self.rsaServerKeyFileName))
        try SecureFiles.write(Array(Self.pem(certificate).utf8), to: url(Self.rsaServerCertificateFileName))
        rsaServer = (certificate, key)
        logger.info("issued RSA RADIUS certificate serial \(Self.hex(certificate.serialNumber), privacy: .public) for \(names.hostnames[0], privacy: .public)")
        return .issued
    }

    /// The RSA RADIUS certificate (nil before `ensureRSAServerCertificate`).
    public func rsaServerCertificate() -> Certificate? { rsaServer?.certificate }

    /// The RSA EAP credential: the RSA leaf, the RSA root, the key as PKCS#8 DER; nil until both exist.
    public func eapRSACredentials() throws -> (chain: [[UInt8]], keyDER: [UInt8])? {
        guard let rsaServer, let ca = try authorityIfExists(named: Self.rsaCompatCAName),
              Self.isIssued(rsaServer.certificate, by: ca.certificate) else { return nil }
        return ([try Self.der(rsaServer.certificate), try ca.der()], try Self.pkcs8DER(rsaServer.key))
    }

    /// PKCS#8 DER of an RSA key (BoringSSL's `EVP_parse_private_key` wants PKCS#8, not PKCS#1).
    static func pkcs8DER(_ key: _RSA.Signing.PrivateKey) throws -> [UInt8] {
        let body = key.pkcs8PEMRepresentation.split(separator: "\n").filter { !$0.hasPrefix("-----") }.joined()
        guard let data = Data(base64Encoded: body) else { throw PKIKitError.encoding("RSA key: PKCS#8 PEM") }
        return Array(data)
    }

    /// Every CA of this DC (DER): what an EAP-TLS client certificate may chain to.
    public func authorityCertificatesDER() throws -> [[UInt8]] {
        try authorities().map { try $0.der() }
    }

    /// The SAN entries of the current server certificate, as issued (host names first).
    public func serverSubjectAltNames() throws -> SubjectAltNames {
        let certificate = try serverCertificate()
        let sans = try? certificate.extensions.subjectAlternativeNames
        var result = SubjectAltNames(hostnames: [], ips: [])
        for name in sans ?? SubjectAlternativeNames() {
            switch name {
            case .dnsName(let host): result.hostnames.append(host)
            case .ipAddress(let octets):
                if let text = NetworkAddresses.format(Array(octets.bytes)) { result.ips.append(text) }
            default: break
            }
        }
        return result
    }

    /// Writes the current CA's certificate (or CA `name`'s) to `url` (0644: it is public) as PEM or DER.
    public func exportCA(name: String? = nil, to url: URL, format: ExportFormat) throws {
        let certificate = try name.map { try authority(named: $0).certificate } ?? caCertificate()
        let bytes: [UInt8]
        switch format {
        case .pem: bytes = Array(try Self.pem(certificate).utf8)
        case .der: bytes = try Self.der(certificate)
        }
        try SecureFiles.write(bytes, to: url, mode: 0o644)
    }

    // MARK: - Internals

    private func url(_ name: String) -> URL {
        directory.appendingPathComponent(name)
    }

    private func load() throws {
        lab = try loadAuthority(name: Self.labCAName, directory: directory)
        server = try loadPair(certificateFile: Self.serverCertificateFileName, keyFile: Self.serverKeyFileName)
        if let certBytes = try SecureFiles.read(url(Self.suiteBServerCertificateFileName)),
           let keyBytes = try SecureFiles.read(url(Self.suiteBServerKeyFileName)),
           let certificate = try? Certificate(pemEncoded: String(decoding: certBytes, as: UTF8.self)),
           let key = try? P384.Signing.PrivateKey(pemRepresentation: String(decoding: keyBytes, as: UTF8.self)),
           Certificate.PublicKey(key.publicKey) == certificate.publicKey {
            suiteBServer = (certificate, key)   // anything else is reissued by the next ensure
        }
        if let certBytes = try SecureFiles.read(url(Self.rsaServerCertificateFileName)),
           let keyBytes = try SecureFiles.read(url(Self.rsaServerKeyFileName)),
           let certificate = try? Certificate(pemEncoded: String(decoding: certBytes, as: UTF8.self)),
           let key = try? _RSA.Signing.PrivateKey(pemRepresentation: String(decoding: keyBytes, as: UTF8.self)),
           Certificate.PublicKey(key.publicKey) == certificate.publicKey {
            rsaServer = (certificate, key)
        }
        if let bytes = try SecureFiles.read(url(Self.currentCAFileName)) {
            guard let object = try? JSONDecoder().decode([String: String].self, from: Data(bytes)),
                  let name = object["current"], !name.isEmpty else {
                throw PKIKitError.corruptFile(path: url(Self.currentCAFileName).path,
                                              reason: "want {\"current\": \"<CA name>\"}")
            }
            currentCAName = name.lowercased() == Self.labCAName ? Self.labCAName : name
        }
    }

    /// Loads `ca.pem` + `ca-key.pem` from `dir` (P-256, P-384 or RSA key). Nil when the certificate is
    /// missing, or its key is missing or does not match (the lab CA is then regenerated).
    private func loadAuthority(name: String, directory dir: URL) throws -> CertificateAuthority? {
        let certURL = dir.appendingPathComponent(Self.caCertificateFileName)
        let keyURL = dir.appendingPathComponent(Self.caKeyFileName)
        guard let certBytes = try SecureFiles.read(certURL) else { return nil }
        guard let keyBytes = try SecureFiles.read(keyURL) else {
            logger.warning("\(certURL.path, privacy: .public) has no key file")
            return nil
        }
        try SecureFiles.restrict(certURL)
        try SecureFiles.restrict(keyURL)
        let certificate: Certificate
        do {
            certificate = try Certificate(pemEncoded: String(decoding: certBytes, as: UTF8.self))
        } catch {
            throw PKIKitError.corruptFile(path: certURL.path, reason: "not a PEM certificate (\(error))")
        }
        let key: CASigningKey
        do {
            key = try CASigningKey(pem: String(decoding: keyBytes, as: UTF8.self))
        } catch {
            throw PKIKitError.corruptFile(path: keyURL.path, reason: "not a P-256, P-384 or RSA PEM private key (\(error))")
        }
        guard key.publicKey == certificate.publicKey else {
            logger.warning("\(keyURL.path, privacy: .public) does not match \(certURL.path, privacy: .public)")
            return nil
        }
        return CertificateAuthority(name: name, certificate: certificate, key: key, directory: dir)
    }

    private func loadPair(certificateFile: String, keyFile: String) throws -> Pair? {
        let certURL = url(certificateFile), keyURL = url(keyFile)
        guard let certBytes = try SecureFiles.read(certURL) else { return nil }
        guard let keyBytes = try SecureFiles.read(keyURL) else {
            logger.warning("\(certificateFile, privacy: .public) has no key file; it will be regenerated")
            return nil
        }
        try SecureFiles.restrict(certURL)
        try SecureFiles.restrict(keyURL)
        let certificate: Certificate
        do {
            certificate = try Certificate(pemEncoded: String(decoding: certBytes, as: UTF8.self))
        } catch {
            throw PKIKitError.corruptFile(path: certURL.path, reason: "not a PEM certificate (\(error))")
        }
        let key: ServerKey
        do {
            key = try ServerKey(pem: String(decoding: keyBytes, as: UTF8.self))
        } catch {
            throw PKIKitError.corruptFile(path: keyURL.path, reason: "not a P-256 or P-384 PEM private key (\(error))")
        }
        guard key.publicKey == certificate.publicKey else {
            logger.warning("\(keyFile, privacy: .public) does not match \(certificateFile, privacy: .public); it will be regenerated")
            return nil
        }
        return Pair(certificate: certificate, key: key)
    }

    /// Key first, then certificate, each via an atomic rename. A crash in between leaves a
    /// mismatching pair, which `loadPair` discards.
    private func write(_ pair: Pair, certificateFile: String, keyFile: String) throws {
        try SecureFiles.write(Array(pair.key.pemRepresentation.utf8), to: url(keyFile))
        try SecureFiles.write(Array(Self.pem(pair.certificate).utf8), to: url(certificateFile))
    }

    static func isIssued(_ certificate: Certificate, by issuer: Certificate) -> Bool {
        certificate.issuer == issuer.subject
            && issuer.publicKey.isValidSignature(certificate.signature, for: certificate)
    }

    struct CanonicalNames {
        var hostnames: [String]
        var ips: [String]
        var generalNames: [GeneralName]
    }

    static func canonicalNames(hostnames: [String], ips: [String]) throws -> CanonicalNames {
        var result = CanonicalNames(hostnames: [], ips: [], generalNames: [])
        var seenHosts = Set<String>()
        for raw in hostnames {
            var host = raw.trimmingCharacters(in: .whitespaces).lowercased()
            if host.hasSuffix(".") { host.removeLast() }
            guard isPlausibleHostname(host) else { throw PKIKitError.invalidHostname(raw) }
            if seenHosts.insert(host).inserted {
                result.hostnames.append(host)
                result.generalNames.append(.dnsName(host))
            }
        }
        guard !result.hostnames.isEmpty else { throw PKIKitError.noHostnames }
        var seenIPs = Set<[UInt8]>()
        for raw in ips {
            let text = raw.trimmingCharacters(in: .whitespaces)
            guard let bytes = NetworkAddresses.parse(text) else { throw PKIKitError.invalidIPAddress(raw) }
            if seenIPs.insert(bytes).inserted {
                result.ips.append(NetworkAddresses.format(bytes) ?? text)
                result.generalNames.append(.ipAddress(ASN1OctetString(contentBytes: bytes[...])))
            }
        }
        return result
    }

    static func isPlausibleHostname(_ host: String) -> Bool {
        guard !host.isEmpty, host.utf8.count <= 253 else { return false }
        for (index, label) in host.split(separator: ".", omittingEmptySubsequences: false).enumerated() {
            guard !label.isEmpty, label.utf8.count <= 63 else { return false }
            if label == "*" && index == 0 { continue }
            for c in label.utf8 {
                let ok = (c >= 0x61 && c <= 0x7A) || (c >= 0x30 && c <= 0x39) || c == 0x2D || c == 0x5F
                if !ok { return false }
            }
        }
        return true
    }

    /// 16 random bytes, top bit clear so the DER INTEGER is positive and stays 16 bytes long.
    static func randomSerial() -> Certificate.SerialNumber {
        var rng = SystemRandomNumberGenerator()
        var bytes = (0..<16).map { _ in UInt8.random(in: 0...255, using: &rng) }
        bytes[0] &= 0x7F
        if bytes[0] == 0 { bytes[0] = 0x01 }
        return Certificate.SerialNumber(bytes: bytes)
    }

    static func pem(_ certificate: Certificate) throws -> String {
        do {
            return try certificate.serializeAsPEM().pemString + "\n"
        } catch {
            throw PKIKitError.encoding("PEM encoding: \(error)")
        }
    }

    static func der(_ certificate: Certificate) throws -> [UInt8] {
        do {
            var serializer = DER.Serializer()
            try serializer.serialize(certificate)
            return serializer.serializedBytes
        } catch {
            throw PKIKitError.encoding("DER encoding: \(error)")
        }
    }

    static func hex(_ serial: Certificate.SerialNumber) -> String {
        serial.bytes.map { String(format: "%02x", $0) }.joined()
    }
}

/// One certificate authority: its certificate and (module-internal) signing key.
public struct CertificateAuthority: Sendable {
    /// `lab` or the name given to `createCA` (used in the CDP/AIA URLs).
    public let name: String
    public let certificate: Certificate
    let key: CASigningKey
    /// Where `ca.pem` / `ca-key.pem` live.
    public let directory: URL

    init(name: String, certificate: Certificate, key: CASigningKey, directory: URL) {
        self.name = name
        self.certificate = certificate
        self.key = key
        self.directory = directory
    }

    public var isLab: Bool { name == LabPKI.labCAName }
    public var keyType: CAKeyType { key.keyType }
    public var certificateURL: URL { directory.appendingPathComponent(LabPKI.caCertificateFileName) }
    /// The subjectKeyIdentifier (the AKI of everything this CA signs).
    public var keyIdentifier: [UInt8]? {
        (try? certificate.extensions.subjectKeyIdentifier?.keyIdentifier).map { Array($0) }
    }
    public func pem() throws -> String { try LabPKI.pem(certificate) }
    public func der() throws -> [UInt8] { try LabPKI.der(certificate) }
}
